CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE "commit" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "commit_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"repositoryWorkId" integer NOT NULL,
	"url" varchar(500) NOT NULL,
	"rawData" jsonb NOT NULL,
	"summary" text,
	"embedding" vector(1536),
	"authoredAt" timestamp with time zone,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "contributor" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "contributor_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"username" varchar(255) NOT NULL,
	"url" varchar(500) NOT NULL,
	"avatarUrl" varchar(500) NOT NULL,
	"summary" text,
	"embedding" vector(1536),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "contributor_username_unique" UNIQUE("username")
);
--> statement-breakpoint
CREATE TABLE "repository" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "repository_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"description" text,
	"url" varchar(500) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "repository_work" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "repository_work_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"repositoryId" integer NOT NULL,
	"contributorId" integer NOT NULL,
	"summary" text,
	"embedding" vector(1536),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "commit" ADD CONSTRAINT "commit_repositoryWorkId_repository_work_id_fk" FOREIGN KEY ("repositoryWorkId") REFERENCES "public"."repository_work"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "repository_work" ADD CONSTRAINT "repository_work_repositoryId_repository_id_fk" FOREIGN KEY ("repositoryId") REFERENCES "public"."repository"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "repository_work" ADD CONSTRAINT "repository_work_contributorId_contributor_id_fk" FOREIGN KEY ("contributorId") REFERENCES "public"."contributor"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "commit_repository_work_idx" ON "commit" USING btree ("repositoryWorkId");--> statement-breakpoint
CREATE INDEX "commit_url_idx" ON "commit" USING btree ("url");--> statement-breakpoint
CREATE INDEX "contributor_username_idx" ON "contributor" USING btree ("username");--> statement-breakpoint
CREATE INDEX "contributor_url_idx" ON "contributor" USING btree ("url");--> statement-breakpoint
CREATE INDEX "repository_name_idx" ON "repository" USING btree ("name");--> statement-breakpoint
CREATE INDEX "repository_url_idx" ON "repository" USING btree ("url");--> statement-breakpoint
CREATE INDEX "repository_work_repo_idx" ON "repository_work" USING btree ("repositoryId");--> statement-breakpoint
CREATE INDEX "repository_work_contributor_idx" ON "repository_work" USING btree ("contributorId");--> statement-breakpoint
CREATE INDEX "repository_work_composite_idx" ON "repository_work" USING btree ("repositoryId","contributorId");